version: "3.7"
services:
  api_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      TZ: Europe/Kiev
    networks:
      - post_beyond
    ports:
    - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api_db
    environment:
      TZ: Europe/Kiev
      DATABASE_URL: postgresql+psycopg2://postgres:test@api_db:5432/api_db
    healthcheck:
      test: curl -sS http://api/ping || echo 1
      interval: 60s
      timeout: 5s
      retries: 5
    networks:
      - post_beyond
    ports:
      - 80:80
    restart: on-failure

networks:
  post_beyond: